spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:toy-hodol
    driver-class-name: org.h2.Driver
    username: sa
    password:

  data:
    web:
      pageable:
        one-indexed-parameters: true # pageable starts at 1 instead of 0