spring:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  docker:
    compose:
      lifecycle-management: start_only

jwt:
  secret-key: +uXZZBWa5RGr+ATqTRPgYFladpxz6ndXPeOoxL+rPTI=