### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "1234"
}

### 인증 페이지 요청 - test
GET http://localhost:8080/posts/foo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.W19SlsPbKD70Dp6JMIWLmkDxPCRdsq49x_0LJDHUQbU